// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYhqOlh1AX9fXRddeJGMYlkiV6Q174980',
    appId: '1:1070939441380:web:4ec119f79f0871b3ee04f1',
    messagingSenderId: '1070939441380',
    projectId: 'appandrew-2e4d1',
    authDomain: 'appandrew-2e4d1.firebaseapp.com',
    storageBucket: 'appandrew-2e4d1.appspot.com',
    measurementId: 'G-1ZX9TTSKE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP35QkL4J3pqAOltbjrOpQUC6B4OOuw0E',
    appId: '1:1070939441380:android:fc51ff163627dc2eee04f1',
    messagingSenderId: '1070939441380',
    projectId: 'appandrew-2e4d1',
    storageBucket: 'appandrew-2e4d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWLvdla1yineER5S-gYol0yQBPsR1yjSM',
    appId: '1:1070939441380:ios:699944a00ac27fecee04f1',
    messagingSenderId: '1070939441380',
    projectId: 'appandrew-2e4d1',
    storageBucket: 'appandrew-2e4d1.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWLvdla1yineER5S-gYol0yQBPsR1yjSM',
    appId: '1:1070939441380:ios:699944a00ac27fecee04f1',
    messagingSenderId: '1070939441380',
    projectId: 'appandrew-2e4d1',
    storageBucket: 'appandrew-2e4d1.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYhqOlh1AX9fXRddeJGMYlkiV6Q174980',
    appId: '1:1070939441380:web:72a5e523d2236168ee04f1',
    messagingSenderId: '1070939441380',
    projectId: 'appandrew-2e4d1',
    authDomain: 'appandrew-2e4d1.firebaseapp.com',
    storageBucket: 'appandrew-2e4d1.appspot.com',
    measurementId: 'G-7KRQWN6GJY',
  );
}
